/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-06-22 18:35:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import libbean.CartDataBean;
import libbean.CartDBBean;
import libbean.CustomerDataBean;
import libbean.CustomerDBBean;
import libbean.BuyDBBean;
import java.util.List;
import java.text.NumberFormat;

public final class buyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("libbean.CustomerDataBean");
    _jspx_imports_classes.add("libbean.CartDataBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("libbean.BuyDBBean");
    _jspx_imports_classes.add("libbean.CartDBBean");
    _jspx_imports_classes.add("java.text.NumberFormat");
    _jspx_imports_classes.add("libbean.CustomerDBBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   String buyer = (String)session.getAttribute("id");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"../sourceboot/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<title></title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("   <a class=\"navbar-brand\" href=\"shopMain.jsp\">캠핑</a>\r\n");
      out.write("  <button class=\"navbar-toggler collapsed\" aria-expanded=\"false\" aria-controls=\"navbarColor01\" aria-label=\"Toggle navigation\" type=\"button\" data-target=\"#navbarColor01\" data-toggle=\"collapse\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"../manager/logon/managerLoginForm.jsp\"> 관리자<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"searchorder.jsp\">주문조회</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("       <a class=\"nav-link\" href=\"../boardfolder/list.jsp\">Q&A 문의</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>    \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");

 try{
   if(session.getAttribute("id")==null){
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\t<div align=\"right\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t      <label for=\"exampleInputEmail1\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t      <form name=\"inform\" method=\"post\" action=\"loginPro.jsp\">\r\n");
      out.write("\t\t\t\t\t\t      <input name=\"id\"  type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"***@***.***\">\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t    \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t      <label for=\"exampleInputPassword1\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t      <input name=\"passwd\" type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"*********\">\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t\t    \t<table>\r\n");
      out.write("\t\t\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<input type=\"submit\" value=\"Login\" name=\"Submit\"  class=\"btn btn-success  btn-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<form method=\"post\" action=\"../insertTestForm.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      \t<input type=\"submit\" value=\"Sign up\" class=\"btn btn-secondary btn-sm\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t</form>\r\n");
      out.write("\t\t\t\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t\t    \t</table>\r\n");
      out.write("\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t    </tr>   \t \t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write(" ");
}else{
      out.write("\r\n");
      out.write(" <br>\r\n");
      out.write(" \r\n");
      out.write("\t <div align=\"right\">\r\n");
      out.write("\t     <b>");
      out.print(session.getAttribute("id"));
      out.write("</b>님\r\n");
      out.write("\t    \r\n");
      out.write("\t    <input type=\"button\"  value=\"장바구니\" onclick=\"javascript:window.location='cartList.jsp?campingitem_kind=all'\" class=\"btn btn-info\">\r\n");
      out.write("\t    <input type=\"button\"  value=\"주문내역\" onclick=\"javascript:window.location='buyList.jsp'\" class=\"btn btn-danger\">\r\n");
      out.write("\t    <input type=\"button\"  value=\"로그아웃\" onclick=\"javascript:window.location='../shop/logout.jsp'\" class=\"btn btn-dark\">\r\n");
      out.write("\t</div>\r\n");
      out.write(" <br>\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write(" ");
}
 }catch(NullPointerException e){
	 e.printStackTrace();
 }
 
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \t<br>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topmiddle.jsp", out, false);
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");

List<CartDataBean> cartLists = null;
List<String> accountLists = null;
CartDataBean cartList = null;
CustomerDataBean member= null;
int number = 0;
int total = 0;

if(session.getAttribute("id")==null){
	response.sendRedirect("shopMain.jsp");        
}else{
	CartDBBean bookProcess = CartDBBean.getInstance();
    cartLists = bookProcess.getCart(buyer);
    
    CustomerDBBean memberProcess = CustomerDBBean.getInstance();
    member = memberProcess.getMember(buyer);
    
    BuyDBBean buyProcess = BuyDBBean.getInstance();
    accountLists = buyProcess.getAccount();

      out.write("\r\n");
      out.write("  <h3><b>구매 목록</b></h3>\r\n");
      out.write("\r\n");
      out.write("  <form name=\"inform\" method=\"post\" action=\"updateCart.jsp\">\r\n");
      out.write("  <table class=\"table table-hover\"> \r\n");
      out.write("    <tr class=\"table-dark\"> \r\n");
      out.write("      <td width=\"40\">No.</td> \r\n");
      out.write("      <td width=\"300\">상품이름</td> \r\n");
      out.write("      <td width=\"100\">판매가격</td>\r\n");
      out.write("      <td width=\"90\">수량</td> \r\n");
      out.write("      <td width=\"110\">금액</td>\r\n");
      out.write("    </tr>   \r\n");

  for(int i=0;i<cartLists.size();i++){
     cartList = cartLists.get(i);

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     <tr> \r\n");
      out.write("       <td width=\"40\">");
      out.print(++number );
      out.write("</td> \r\n");
      out.write("       <td width=\"300\" align=\"left\">\r\n");
      out.write("         <img src=\"../photofile/");
      out.print(cartList.getCampingitem_image());
      out.write("\" \r\n");
      out.write("           border=\"0\" width=\"30\" height=\"50\" align=\"middle\">\r\n");
      out.write("           ");
      out.print(cartList.getCampingitem_title());
      out.write("\r\n");
      out.write("       </td> \r\n");
      out.write("       <td width=\"100\">");
      out.print(NumberFormat.getInstance().format(cartList.getBuy_price()));
      out.write("</td>\r\n");
      out.write("       <td width=\"90\">");
      out.print(cartList.getBuy_count());
      out.write("</td> \r\n");
      out.write("       <td width=\"110\">\r\n");
      out.write("          ");
total += cartList.getBuy_count()*cartList.getBuy_price();
      out.write("\r\n");
      out.write("          ");
      out.print(NumberFormat.getInstance().format(cartList.getBuy_count()*cartList.getBuy_price()) );
      out.write("\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");

  }

      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"5\" align=\"right\"><b>총 구매금액 : ");
      out.print(NumberFormat.getInstance().format(total));
      out.write("</b></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
} 
 
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("  <h3><b>주문자 정보</b></h3>\r\n");
      out.write("<form method=\"post\" action=\"buyPro.jsp\" name=\"buyinput\">\r\n");
      out.write(" <table class=\"table table-hover\">\r\n");
      out.write("   <tr class=\"table-dark\"> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">이름</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">");
      out.print(member.getName());
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"table-dark\"> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">전화번호</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">");
      out.print(member.getTel());
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"table-dark\"> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">휴대전화</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">");
      out.print(member.getPhone_tel());
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"table-dark\"> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">우편번호</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">");
      out.print(member.getAddress_number());
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"table-dark\"> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">배송지 주소</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">");
      out.print(member.getAddress());
      out.write("</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr class=\"table-dark\"> \r\n");
      out.write("     <td  width=\"200\" align=\"left\">결제 업체 계좌</td>\r\n");
      out.write("     <td  width=\"400\" align=\"left\">\r\n");
      out.write("       <select name=\"account\">\r\n");
      out.write("        ");

          for(int i=0;i<accountLists.size();i++){
           String accountList = accountLists.get(i);
         
      out.write("\r\n");
      out.write("           <option value=\"");
      out.print(accountList );
      out.write('"');
      out.write('>');
      out.print(accountList );
      out.write("</option>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("       </select>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  <br>\r\n");
      out.write("   \r\n");
      out.write(" <h3><b>배송지 정보</b></h3>\r\n");
      out.write(" \r\n");
      out.write("<table class=\"table table-hover\">\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">성명</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("      <input type=\"text\" name=\"deliveryName\" value=\"");
      out.print(member.getName());
      out.write("\">\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">휴대전화</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("      <input type=\"text\" name=\"deliveryTel\" value=\"");
      out.print(member.getPhone_tel());
      out.write("\">\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">우편번호</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("      <input type=\"text\" name=\"deliveryAddessNum\" value=\"");
      out.print(member.getAddress_number());
      out.write("\">\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr> \r\n");
      out.write("    <td  width=\"200\" align=\"left\">주소</td>\r\n");
      out.write("    <td  width=\"400\" align=\"left\">\r\n");
      out.write("      <input type=\"text\" name=\"deliveryAddess\" value=\"");
      out.print(member.getAddress());
      out.write("\">\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("   <input type=\"hidden\" name=\"email\" value=\"");
      out.print(session.getAttribute("id"));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("   <tr> \r\n");
      out.write("     <td colspan=\"2\" align=\"center\">\r\n");
      out.write("       <input type=\"submit\" value=\"확인\"  class=\"btn btn-primary\">\r\n");
      out.write("       <input type=\"button\" value=\"취소\" class=\"btn btn-dark\"\r\n");
      out.write("       onclick=\"javascript:window.location='cartList.jsp?campingitem_kind=all'\">      \r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
