/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-06-09 14:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Timestamp;
import libbean.ShopCampingitemDBBean;
import libbean.ShopCampingitemDataBean;

public final class campingUpdateForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("libbean.ShopCampingitemDBBean");
    _jspx_imports_classes.add("libbean.ShopCampingitemDataBean");
    _jspx_imports_classes.add("java.sql.Timestamp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");

String managerId ="";
try{
   managerId = (String)session.getAttribute("managerId");
   if(managerId==null || managerId.equals("")){
      response.sendRedirect("../logon/managerLoginForm.jsp");
}else{

      out.write('\r');
      out.write('\n');

int campingitem_id = Integer.parseInt(request.getParameter("campingitem_id"));
String campingitem_kind = request.getParameter("campingitem_kind");
try{
	ShopCampingitemDBBean campingProcess = ShopCampingitemDBBean.getInstance();
    ShopCampingitemDataBean camping =  campingProcess.getcampingitem(campingitem_id); 

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>상품수정</title>\r\n");
      out.write("<link href=\"../sourceboot/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\">\r\n");
      out.write("  \t\t<a class=\"navbar-brand\" href=\"#\">상품관리</a>\r\n");
      out.write("    \t\t<div class=\"text-right\" align=\"right\">\r\n");
      out.write("    \t\t<table>\r\n");
      out.write("\t    \t\t<tr>\r\n");
      out.write("\t    \t\t\t<td>\r\n");
      out.write("\t\t    \t\t\t<form method=\"post\" action=\"managerMain.jsp\"> \r\n");
      out.write("\t\t\t\t\t\t    <input type=\"submit\" value=\"홈\" class=\"btn btn-dark\">\t\r\n");
      out.write("\t\t\t\t\t\t </form>\r\n");
      out.write("\t\t\t\t\t </td>\r\n");
      out.write("\t\t\t\t\t <td>\t\r\n");
      out.write("\t\t\t\t    \t<form method=\"post\" action=\"../manager/campingList.jsp?campingitem_kind=all\"> \r\n");
      out.write("\t\t\t\t   \t    \t<input type=\"submit\" value=\"뒤로 가기\" class=\"btn btn-dark\">\t\r\n");
      out.write("\t\t\t\t    \t</form>\r\n");
      out.write("\t\t\t    \t</td>\r\n");
      out.write("\t\t\t    </tr>\t\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("    \t\t\r\n");
      out.write("\t   \t    </div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div class=\"text-right\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t  <form method=\"post\" action=\"campingList.jsp?campingitem_kind=");
      out.print(campingitem_kind);
      out.write("\"> \r\n");
      out.write("\t\t\t\t  <input type=\"submit\" value=\"선택한 분류 확인하기\" class=\"btn btn-outline-success\">\t\r\n");
      out.write("\t\t\t  </form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t </table>\t  \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<form method=\"post\" name=\"writeform\" \r\n");
      out.write("\t   action=\"campingUpdatePro.jsp\"  enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\"\" align=\"center\">종류</td>\r\n");
      out.write("\t\t    <td  width=\"400\"  align=\"left\">\r\n");
      out.write("\t\t       <select name=\"campingitem_kind\" class=\"custom-select\">\r\n");
      out.write("\t\t           <option value=\"100\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("100")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t              >랜턴 | 버너</option>\r\n");
      out.write("\t\t           <option value=\"200\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("200")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >캠핑퍼니처</option>\r\n");
      out.write("\t\t          <option value=\"300\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("300")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >침낭 | 매트</option>\r\n");
      out.write("\t\t          <option value=\"400\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("400")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >텐트 | 천막</option>\r\n");
      out.write("\t\t              <option value=\"500\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("500")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >의류</option>\r\n");
      out.write("\t\t              <option value=\"600\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("600")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >신발</option>\r\n");
      out.write("\t\t              <option value=\"700\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("700")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >가방</option>\r\n");
      out.write("\t\t              <option value=\"800\" \r\n");
      out.write("\t\t             ");
if (camping.getCampingitem_kind().equals("800")) {
      out.write("selected");
} 
      out.write("\r\n");
      out.write("\t\t             >주변 도구</option>\r\n");
      out.write("\t\t       </select>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">업체명</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"50\" maxlength=\"50\" name=\"campingitem_makername\" \r\n");
      out.write("\t\t            value=\"");
      out.print(camping.getCampingitem_makername() );
      out.write("\">\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">제품명</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"50\" maxlength=\"50\" name=\"campingitem_title\" \r\n");
      out.write("\t\t            value=\"");
      out.print(camping.getCampingitem_title() );
      out.write("\">\r\n");
      out.write("\t\t       <input type=\"hidden\" name=\"campingitem_id\" value=\"");
      out.print(campingitem_id);
      out.write("\"> </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">가 격</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"9\" name=\"campingitem_price\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_price() );
      out.write("\">원</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">수량</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"5\" name=\"campingitem_count\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_count() );
      out.write("\">개</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t     <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">출시년월</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"5\" name=\"campingitem_launched\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_launched());
      out.write("\"></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">재질</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"5\" name=\"campingitem_material\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_material());
      out.write("\"></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">색상</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"30\" name=\"campingitem_color\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_color() );
      out.write("\"></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">사이즈</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"30\" name=\"campingitem_size\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_weight());
      out.write("\"></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">무게</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"10\" maxlength=\"30\" name=\"campingitem_weight\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_weight() );
      out.write("\">g 단위</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">이미지</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"file\" name=\"campingitem_image\">현재 이미지 :  ");
      out.print(camping.getCampingitem_image() );
      out.write("</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">내 용</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t     <textarea name=\"campingitem_content \" rows=\"13\" \r\n");
      out.write("\t\t         cols=\"40\">");
      out.print(camping.getCampingitem_content() );
      out.write("</textarea> </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("\t\t    <td  width=\"100\"  class=\"table-warning\" align=\"center\">할인율</td>\r\n");
      out.write("\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t        <input type=\"text\" size=\"5\" maxlength=\"2\" name=\"campingitem_discount_rate\" \r\n");
      out.write("\t\t          value=\"");
      out.print(camping.getCampingitem_discount_rate() );
      out.write("\">%</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-bottom\">\r\n");
      out.write("\t\t\t\t  \t<div class=\"text-right\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"수정\" onclick=\"updateCheckForm(this.form)\" class=\"btn btn-outline-success\">  \r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"다시작성\"  class=\"btn btn-outline-warning\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t         \r\n");
      out.write("\t</form>   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

}catch(Exception e){
	e.printStackTrace();
}
      out.write("         \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
 
  }
}catch(Exception e){
	e.printStackTrace();
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
