/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-06-22 14:39:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Timestamp;

public final class campingRegisterForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Timestamp");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   String managerId ="";
   try{
	   managerId = (String)session.getAttribute("managerId");
	   if(managerId==null || managerId.equals("")){
           response.sendRedirect("../logon/managerLoginForm.jsp");
	   }else{

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>상품등록</title>\r\n");
      out.write("<link href=\"../sourceboot/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-top\">\r\n");
      out.write("  \t\t<a class=\"navbar-brand\" href=\"#\">상품등록</a>\r\n");
      out.write("    \t\t<div class=\"text-right\" align=\"right\">\r\n");
      out.write("\t\t    \t<form method=\"post\" action=\"managerMain.jsp\"> \r\n");
      out.write("\t\t   \t    \t<input type=\"submit\" value=\"뒤로 가기\" class=\"btn btn-dark\">\t\r\n");
      out.write("\t\t    \t</form>\t\r\n");
      out.write("\t\t    \r\n");
      out.write("\t   \t    </div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("<br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<form method=\"post\" name=\"writeform\" \r\n");
      out.write("\t\t\t     action=\"campingRegisterPro.jsp\"  enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\"\" align=\"center\">종류(품번)</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t       <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t       <select name=\"campingitem_kind\" class=\"custom-select\">\r\n");
      out.write("\t\t\t\t           <option value=\"100\">랜턴 | 버너</option>       <!--Leather  -->\r\n");
      out.write("\t\t\t\t           <option value=\"200\">캠핑퍼니처</option>   <!--Gold  -->\r\n");
      out.write("\t\t\t\t           <option value=\"300\">침낭 | 매트</option>   <!--Silver  -->\r\n");
      out.write("\t\t\t\t           <option value=\"400\">텐트 | 천막</option>   <!--Black  -->\r\n");
      out.write("\t\t\t\t           <option value=\"500\">의류</option> \r\n");
      out.write("\t\t\t\t           <option value=\"600\">신발</option> \r\n");
      out.write("\t\t\t\t           <option value=\"700\">가방</option> \r\n");
      out.write("\t\t\t\t           <option value=\"800\">주변 도구</option> \r\n");
      out.write("\t\t\t\t       </select>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t    </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">업체명</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"50\" maxlength=\"50\" name=\"campingitem_makername\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">제품명</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"50\" maxlength=\"50\" name=\"campingitem_title\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\"  class=\"table-success\" align=\"center\">가 격</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"20\" name=\"campingitem_price\" class=\"form-control\" placeholder=\"#######\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">수 량</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"5\" name=\"campingitem_count\" class=\"form-control\" placeholder=\"#\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">출시년월</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"15\" name=\"campingitem_launched\" class=\"form-control\" placeholder=\"##년-##월\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">재질</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"30\" name=\"campingitem_material\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">색상</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"30\" name=\"campingitem_color\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\"  class=\"table-success\" align=\"center\">사이즈</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"40\" name=\"campingitem_size\" class=\"form-control\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t   <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\"  class=\"table-success\" align=\"center\">무 게</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"10\" maxlength=\"30\" name=\"campingitem_weight\" class=\"form-control\" placeholder=\"g 단위\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\"  class=\"table-success\" align=\"center\">이미지</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"file\" name=\"campingitem_image\"></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\" class=\"table-success\" align=\"center\">설 명</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t     <textarea name=\"campingitem_content\" rows=\"13\" cols=\"40\" class=\"form-control\"></textarea> </td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("\t\t\t    <td  width=\"100\"  class=\"table-danger\" align=\"center\">할인율</td>\r\n");
      out.write("\t\t\t    <td  width=\"400\" align=\"left\">\r\n");
      out.write("\t\t\t        <input type=\"text\" size=\"5\" maxlength=\"4\" name=\"campingitem_discount_rate\" class=\"form-control\" placeholder=\"%\"></td>\r\n");
      out.write("\t\t\t  </tr>  \r\n");
      out.write("\t\t</table> \r\n");
      out.write("\t\t<br><Br><br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light fixed-bottom\">\r\n");
      out.write("\t\t\t\t  \t<div class=\"text-right\" align=\"right\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"상품등록\" onclick=\"checkForm(this.form)\" class=\"btn btn-outline-success\">  \r\n");
      out.write("\t\t\t\t\t\t<input type=\"reset\" value=\"다시작성\"  class=\"btn btn-outline-warning\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 

		}
	}catch(Exception e){
		e.printStackTrace();
	}
	   

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
