/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-06-24 04:52:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertTestForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"sourceboot/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("   <a class=\"navbar-brand\" href=\"shop/shopMain.jsp\">캠핑</a>\r\n");
      out.write("  <button class=\"navbar-toggler collapsed\" aria-expanded=\"false\" aria-controls=\"navbarColor01\" aria-label=\"Toggle navigation\" type=\"button\" data-target=\"#navbarColor01\" data-toggle=\"collapse\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"manager/logon/managerLoginForm.jsp\"> 관리자<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link\" href=\"shop/searchorder.jsp\">주문조회</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("       <a class=\"nav-link\" href=\"boardfolder/list.jsp\">Q&A 문의</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>    \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t<div class=\"text-center jumbotron\">\r\n");
      out.write("\t\t \t\t <h2>사용할 ID를 확인해주세요!!!</h2> <br>\r\n");
      out.write("\t\t\t\t\t<table align =\"center\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<form method=\"post\" action=\"idconfirmpro.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"confirmid\" maxlength=\"50\"   placeholder=\"ID\" style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t\t    <td>\t\r\n");
      out.write("\t\t\t\t\t\t    \t<input type=\"submit\" value=\"중복확인\" class=\"btn btn-dark\">\r\n");
      out.write("\t\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t\t    \t</form>\t\t    \t\r\n");
      out.write("\t\t\t\t\t    </tr>\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t    </div>\t\t\t\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"text-center jumbotron\">\r\n");
      out.write("\t\t  <h2>회원가입</h2> <br>\r\n");
      out.write("\t\t    <table align =\"center\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t    <form method=\"post\" action=\"insertTestPro.jsp\">\r\n");
      out.write("\t\t\t        <td>ID</td> \r\n");
      out.write("\t\t\t        <td><input type=\"text\" name=\"id\" maxlength=\"50\"   placeholder=\"ID\" style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t     </tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t      <tr>\r\n");
      out.write("\t\t\t        <td>PASSWORD</td> <td><input type=\"password\" name=\"passwd\" maxlength=\"16\" placeholder=\"Password\"\r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t       </tr>\r\n");
      out.write("\t\t\t        <tr>\r\n");
      out.write("\t\t\t          <td>이름</td> <td><input type=\"text\" name=\"name\" maxlength=\"10\" \r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t          </tr>\r\n");
      out.write("\t\t\t          <tr>\r\n");
      out.write("\t\t\t            <td>우편주소</td> <td><input type=\"text\" name=\"address_number\" maxlength=\"10\" \r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr>\r\n");
      out.write("\t\t\t             <td> 주소</td> <td><input type=\"text\" name=\"address\" maxlength=\"30\"   \r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t             </tr>\r\n");
      out.write("\t\t\t             <tr>\r\n");
      out.write("\t\t\t              <td>전화번호</td> <td><input type=\"text\" name=\"tel\" maxlength=\"14\"   placeholder=\"031-###-####\"\r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t               </tr>\r\n");
      out.write("\t\t\t              <tr>\r\n");
      out.write("\t\t\t        <td> 핸드폰</td> <td><input type=\"text\" name=\"phone_tel\" maxlength=\"14\"   placeholder=\"010-####-####\"\r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t             </tr>\r\n");
      out.write("\t\t\t             \r\n");
      out.write("\t\t\t             \r\n");
      out.write("\t\t\t             \r\n");
      out.write("\t\t\t             \r\n");
      out.write("\t\t\t               <tr>\r\n");
      out.write("\t\t\t        <td> 생년월일</td> <td><input type=\"text\" name=\"birthday\" maxlength=\"14\"   placeholder=\"####-##-##\"\r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t             </tr>\r\n");
      out.write("\t\t\t               <tr>\r\n");
      out.write("\t\t\t        <td> 성별</td> <td><input type=\"text\" name=\"sex\" maxlength=\"14\"   placeholder=\"남자  or 여자\"\r\n");
      out.write("\t\t\t               style=\"ime-mode:inactive;\"><br></td>\r\n");
      out.write("\t\t\t             </tr>\r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t             \r\n");
      out.write("\t\t       </table>        \r\n");
      out.write("\t\t               <br>\r\n");
      out.write("\t\t               \r\n");
      out.write("\t\t               \r\n");
      out.write("            <table align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("\t\t\t        <input type=\"submit\" value=\"입력완료\" class=\"btn btn-dark\">\r\n");
      out.write("\t\t\t    </form>\r\n");
      out.write("\t\t\t</td> \r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t <td>\r\n");
      out.write("\t\t\t     <form method=\"post\" action=\"shop/shopMain.jsp\">\r\n");
      out.write("\t\t\t\t\t    \t  <input type=\"submit\" value=\"상점이동\" class=\"btn btn-dark\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("  \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
