/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.41
 * Generated at: 2019-06-09 20:06:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"sourceboot/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>캠핑</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-primary\">\r\n");
      out.write("   <a class=\"navbar-brand\" href=\"shop/shopMain.jsp\">캠핑</a>\r\n");
      out.write("  <button class=\"navbar-toggler collapsed\" aria-expanded=\"false\" aria-controls=\"navbarColor01\" aria-label=\"Toggle navigation\" type=\"button\" data-target=\"#navbarColor01\" data-toggle=\"collapse\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarColor01\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"manager/logon/managerLoginForm.jsp\"> 관리자<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("       <a class=\"nav-link\" href=\"#\">주문조회</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("         <a class=\"nav-link\" href=\"#\">고객후기</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("       <a class=\"nav-link\" href=\"boardfolder/list.jsp\">Q&A 문의</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>    \r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t<div align=\"right\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t      <label for=\"exampleInputEmail1\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t      <form method=\"post\" action=\"customer/clogon/customerLoginPro.jsp\">\r\n");
      out.write("\t\t\t\t\t\t      <input name=\"id\"  type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"***@***.***\">\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t    \t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t      <label for=\"exampleInputPassword1\">Password</label>\r\n");
      out.write("\t\t\t\t\t\t      <input name=\"passwd\" type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"*********\">\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t\t    \t<table>\r\n");
      out.write("\t\t\t\t\t\t    \t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<input type=\"submit\" value=\"Login\" class=\"btn btn-success  btn-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t    \t<td>\r\n");
      out.write("\t\t\t\t\t\t\t    \t\t<form method=\"post\" action=\"insertTestForm.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      \t<input type=\"submit\" value=\"Sign up\" class=\"btn btn-secondary btn-sm\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t</form>\r\n");
      out.write("\t\t\t\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t\t\t    \t</tr>\r\n");
      out.write("\t\t\t\t\t    \t</table>\r\n");
      out.write("\t\t\t\t    \t</td>\r\n");
      out.write("\t\t\t\t    </tr>   \t \t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h1> </h1>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("\t  <a class=\"navbar-brand\" href=\"shop/list.jsp?clock_kind=all\">ALL</a>\r\n");
      out.write("\t  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarColor03\" aria-controls=\"navbarColor03\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t  </button>\r\n");
      out.write("\t\r\n");
      out.write("\t  <div class=\"collapse navbar-collapse\" id=\"navbarColor03\">\r\n");
      out.write("\t    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("\t      <li class=\"nav-item\">\r\n");
      out.write("\t        <a class=\"nav-link\" href=\"shop/list.jsp?clock_kind=100\">- Leather</a>\r\n");
      out.write("\t      </li>\r\n");
      out.write("\t      <li class=\"nav-item\">\r\n");
      out.write("\t        <a class=\"nav-link\" href=\"shop/list.jsp?clock_kind=200\">- Gold</a>\r\n");
      out.write("\t      </li>\r\n");
      out.write("\t      <li class=\"nav-item\">\r\n");
      out.write("\t        <a class=\"nav-link\" href=\"shop/list.jsp?clock_kind=300\">- Silver</a>\r\n");
      out.write("\t      </li>\r\n");
      out.write("\t      <li class=\"nav-item\">\r\n");
      out.write("\t        <a class=\"nav-link\" href=\"shop/list.jsp?clock_kind=400\">- Black</a>\r\n");
      out.write("\t      </li>\r\n");
      out.write("\t    </ul>\r\n");
      out.write("\t    <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("\t      <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\">\r\n");
      out.write("\t      <button class=\"btn btn-secondary my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("\t    </form>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t  <div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("\t    <a href=\"#\" class=\"thumbnail\">\r\n");
      out.write("\t      <img src=\"photofile/4000003.jpg\">\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("\t    <a href=\"#\" class=\"thumbnail\">\r\n");
      out.write("\t      <img src=\"photofile/2000006.jpg\">\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("\t    <a href=\"#\" class=\"thumbnail\">\r\n");
      out.write("\t      <img src=\"photofile/1000001.jpg\">\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <div class=\"col-xs-6 col-md-3\">\r\n");
      out.write("\t    <a href=\"#\" class=\"thumbnail\">\r\n");
      out.write("\t      <img src=\"photofile/1000004.jpg\">\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("    \r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-info\">Facebook</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-warning\">KaTalk</button>\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-outline-danger\">Instagram</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("    <blockquote class=\"blockquote text-center\">\r\n");
      out.write("\t  <p class=\"mb-0\">BANK INFO</p>\r\n");
      out.write("\t  <p class=\"mb-0\">신한금융투자</p>\r\n");
      out.write("\t  <p class=\"mb-0\">270-22-591047</p>\r\n");
      out.write("\t</blockquote>\r\n");
      out.write("\t\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t<button type=\"button\" class=\"btn btn-secondary\" title=\"\" data-container=\"body\" data-toggle=\"popover\" data-placement=\"top\" data-content=\"이희창(2015114022) 김충식(2015114007) 이상현(2015114018) 공태현(2015114002)\" data-original-title=\"Team\">팀원</button>\r\n");
      out.write("\t\t<span class=\"badge badge-dark\">이희창</span>\r\n");
      out.write("\t\t<span class=\"badge badge-warning\">김충식</span>\r\n");
      out.write("\t\t<span class=\"badge badge-success\">공태현</span>\r\n");
      out.write("\t\t<span class=\"badge badge-info\">이상현</span>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
